# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountsDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 450))
        Dialog.setMaximumSize(QtCore.QSize(400, 450))
        Dialog.setModal(True)
        self.listWidgetAccount = QtWidgets.QListWidget(Dialog)
        self.listWidgetAccount.setGeometry(QtCore.QRect(130, 20, 250, 200))
        self.listWidgetAccount.setObjectName("listWidgetAccount")
        self.pushButtonNew = QtWidgets.QPushButton(Dialog)
        self.pushButtonNew.setGeometry(QtCore.QRect(20, 20, 100, 25))
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonEdit = QtWidgets.QPushButton(Dialog)
        self.pushButtonEdit.setGeometry(QtCore.QRect(20, 50, 100, 25))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.pushButtonDelete = QtWidgets.QPushButton(Dialog)
        self.pushButtonDelete.setGeometry(QtCore.QRect(20, 80, 100, 25))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.labelOwner = QtWidgets.QLabel(Dialog)
        self.labelOwner.setGeometry(QtCore.QRect(30, 290, 100, 20))
        self.labelOwner.setObjectName("labelOwner")
        self.lineEditAccount = QtWidgets.QLineEdit(Dialog)
        self.lineEditAccount.setEnabled(False)
        self.lineEditAccount.setGeometry(QtCore.QRect(130, 230, 250, 20))
        self.lineEditAccount.setObjectName("lineEditAccount")
        self.labelType = QtWidgets.QLabel(Dialog)
        self.labelType.setGeometry(QtCore.QRect(30, 260, 100, 20))
        self.labelType.setObjectName("labelType")
        self.lineEditBank = QtWidgets.QLineEdit(Dialog)
        self.lineEditBank.setEnabled(False)
        self.lineEditBank.setGeometry(QtCore.QRect(130, 320, 250, 20))
        self.lineEditBank.setObjectName("lineEditBank")
        self.labelAccount = QtWidgets.QLabel(Dialog)
        self.labelAccount.setEnabled(True)
        self.labelAccount.setGeometry(QtCore.QRect(30, 230, 100, 20))
        self.labelAccount.setObjectName("labelAccount")
        self.lineEditPrimary = QtWidgets.QLineEdit(Dialog)
        self.lineEditPrimary.setEnabled(False)
        self.lineEditPrimary.setGeometry(QtCore.QRect(130, 290, 250, 20))
        self.lineEditPrimary.setObjectName("lineEditPrimary")
        self.pushButtonSubmit = QtWidgets.QPushButton(Dialog)
        self.pushButtonSubmit.setEnabled(False)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(257, 410, 125, 25))
        self.pushButtonSubmit.setAutoRepeatDelay(305)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.comboBoxATypes = QtWidgets.QComboBox(Dialog)
        self.comboBoxATypes.setEnabled(False)
        self.comboBoxATypes.setGeometry(QtCore.QRect(130, 260, 201, 22))
        self.comboBoxATypes.setObjectName("comboBoxATypes")
        self.labelBank = QtWidgets.QLabel(Dialog)
        self.labelBank.setGeometry(QtCore.QRect(30, 320, 100, 20))
        self.labelBank.setObjectName("labelBank")
        self.labelError = QtWidgets.QLabel(Dialog)
        self.labelError.setEnabled(True)
        self.labelError.setGeometry(QtCore.QRect(30, 410, 211, 25))
        self.labelError.setText("")
        self.labelError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelError.setObjectName("labelError")
        self.pushButtonModify = QtWidgets.QPushButton(Dialog)
        self.pushButtonModify.setEnabled(False)
        self.pushButtonModify.setGeometry(QtCore.QRect(257, 410, 125, 25))
        self.pushButtonModify.setAutoRepeatDelay(305)
        self.pushButtonModify.setObjectName("pushButtonModify")
        self.pushButtonMod = QtWidgets.QPushButton(Dialog)
        self.pushButtonMod.setEnabled(False)
        self.pushButtonMod.setGeometry(QtCore.QRect(340, 260, 41, 23))
        self.pushButtonMod.setObjectName("pushButtonMod")
        self.labelVariable1 = QtWidgets.QLabel(Dialog)
        self.labelVariable1.setGeometry(QtCore.QRect(30, 350, 100, 20))
        self.labelVariable1.setObjectName("labelVariable1")
        self.lineEditVariable1 = QtWidgets.QLineEdit(Dialog)
        self.lineEditVariable1.setEnabled(False)
        self.lineEditVariable1.setGeometry(QtCore.QRect(130, 350, 250, 20))
        self.lineEditVariable1.setObjectName("lineEditVariable1")
        self.labelVariable2 = QtWidgets.QLabel(Dialog)
        self.labelVariable2.setGeometry(QtCore.QRect(30, 380, 100, 20))
        self.labelVariable2.setObjectName("labelVariable2")
        self.lineEditVariable2 = QtWidgets.QLineEdit(Dialog)
        self.lineEditVariable2.setEnabled(False)
        self.lineEditVariable2.setGeometry(QtCore.QRect(130, 380, 250, 20))
        self.lineEditVariable2.setObjectName("lineEditVariable2")
        self.pushButtonArchive = QtWidgets.QPushButton(Dialog)
        self.pushButtonArchive.setEnabled(True)
        self.pushButtonArchive.setGeometry(QtCore.QRect(20, 110, 100, 25))
        self.pushButtonArchive.setObjectName("pushButtonArchive")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.listWidgetAccount, self.pushButtonNew)
        Dialog.setTabOrder(self.pushButtonNew, self.pushButtonEdit)
        Dialog.setTabOrder(self.pushButtonEdit, self.pushButtonDelete)
        Dialog.setTabOrder(self.pushButtonDelete, self.pushButtonArchive)
        Dialog.setTabOrder(self.pushButtonArchive, self.lineEditAccount)
        Dialog.setTabOrder(self.lineEditAccount, self.comboBoxATypes)
        Dialog.setTabOrder(self.comboBoxATypes, self.pushButtonMod)
        Dialog.setTabOrder(self.pushButtonMod, self.lineEditPrimary)
        Dialog.setTabOrder(self.lineEditPrimary, self.lineEditBank)
        Dialog.setTabOrder(self.lineEditBank, self.lineEditVariable1)
        Dialog.setTabOrder(self.lineEditVariable1, self.lineEditVariable2)
        Dialog.setTabOrder(self.lineEditVariable2, self.pushButtonSubmit)
        Dialog.setTabOrder(self.pushButtonSubmit, self.pushButtonModify)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modify Available Accounts"))
        self.listWidgetAccount.setSortingEnabled(True)
        self.pushButtonNew.setText(_translate("Dialog", "New"))
        self.pushButtonEdit.setText(_translate("Dialog", "Edit"))
        self.pushButtonDelete.setText(_translate("Dialog", "Delete"))
        self.labelOwner.setText(_translate("Dialog", "Primary Owner:"))
        self.labelType.setText(_translate("Dialog", "Account Type:"))
        self.labelAccount.setText(_translate("Dialog", "Account Name:"))
        self.pushButtonSubmit.setText(_translate("Dialog", "Submit"))
        self.labelBank.setText(_translate("Dialog", "Bank:"))
        self.pushButtonModify.setText(_translate("Dialog", "Submit Edit"))
        self.pushButtonMod.setText(_translate("Dialog", "Modify"))
        self.labelVariable1.setText(_translate("Dialog", "Interest Rate:"))
        self.labelVariable2.setText(_translate("Dialog", "Maturity Date:"))
        self.pushButtonArchive.setText(_translate("Dialog", "Archive"))


