# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CategoriesDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 400))
        Dialog.setMaximumSize(QtCore.QSize(300, 400))
        Dialog.setWindowIcon(QtGui.QIcon('Beaker Labs llc Logo.png'))
        self.listWidgetCategory = QtWidgets.QListWidget(Dialog)
        self.listWidgetCategory.setGeometry(QtCore.QRect(25, 60, 250, 200))
        self.listWidgetCategory.setObjectName("listWidgetCategory")
        self.labelHeader = QtWidgets.QLabel(Dialog)
        self.labelHeader.setGeometry(QtCore.QRect(25, 20, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHeader.setFont(font)
        self.labelHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader.setObjectName("labelHeader")
        self.labelModifier = QtWidgets.QLabel(Dialog)
        self.labelModifier.setGeometry(QtCore.QRect(25, 280, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModifier.setFont(font)
        self.labelModifier.setAlignment(QtCore.Qt.AlignCenter)
        self.labelModifier.setObjectName("labelModifier")
        self.lineEditMethod = QtWidgets.QLineEdit(Dialog)
        self.lineEditMethod.setGeometry(QtCore.QRect(25, 300, 250, 20))
        self.lineEditMethod.setObjectName("lineEditMethod")
        self.pushButtonNew = QtWidgets.QPushButton(Dialog)
        self.pushButtonNew.setGeometry(QtCore.QRect(25, 330, 76, 25))
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonEdit = QtWidgets.QPushButton(Dialog)
        self.pushButtonEdit.setGeometry(QtCore.QRect(112, 330, 76, 25))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.pushButtonDelete = QtWidgets.QPushButton(Dialog)
        self.pushButtonDelete.setGeometry(QtCore.QRect(200, 330, 76, 25))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonNewSubmit = QtWidgets.QPushButton(Dialog)
        self.pushButtonNewSubmit.setEnabled(False)
        self.pushButtonNewSubmit.setGeometry(QtCore.QRect(25, 330, 76, 25))
        self.pushButtonNewSubmit.setObjectName("pushButtonNewSubmit")
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setEnabled(False)
        self.pushButtonCancel.setGeometry(QtCore.QRect(200, 330, 76, 25))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.pushButtonEditSubmit = QtWidgets.QPushButton(Dialog)
        self.pushButtonEditSubmit.setEnabled(False)
        self.pushButtonEditSubmit.setGeometry(QtCore.QRect(112, 330, 76, 25))
        self.pushButtonEditSubmit.setObjectName("pushButtonEditSubmit")
        self.labelParentType = QtWidgets.QLabel(Dialog)
        self.labelParentType.setGeometry(QtCore.QRect(25, 40, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelParentType.setFont(font)
        self.labelParentType.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParentType.setObjectName("labelParentType")
        self.labelError = QtWidgets.QLabel(Dialog)
        self.labelError.setGeometry(QtCore.QRect(25, 360, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelError.setFont(font)
        self.labelError.setText("")
        self.labelError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelError.setObjectName("labelError")
        self.pushButtonNewSubmit.raise_()
        self.pushButtonEditSubmit.raise_()
        self.pushButtonCancel.raise_()
        self.listWidgetCategory.raise_()
        self.labelHeader.raise_()
        self.labelModifier.raise_()
        self.lineEditMethod.raise_()
        self.pushButtonNew.raise_()
        self.pushButtonEdit.raise_()
        self.pushButtonDelete.raise_()
        self.labelParentType.raise_()
        self.labelError.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Transaction Methods"))
        self.listWidgetCategory.setSortingEnabled(True)
        self.labelHeader.setText(_translate("Dialog", "Bank Account"))
        self.labelModifier.setText(_translate("Dialog", "Selected Transaction Method:"))
        self.pushButtonNew.setText(_translate("Dialog", "New"))
        self.pushButtonEdit.setText(_translate("Dialog", "Edit"))
        self.pushButtonDelete.setText(_translate("Dialog", "Delete"))
        self.pushButtonNewSubmit.setText(_translate("Dialog", "Submit"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.pushButtonEditSubmit.setText(_translate("Dialog", "Submit"))
        self.labelParentType.setText(_translate("Dialog", "Transaction Methods"))

