# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ledger1Ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 798)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.labelStaticL11 = QtWidgets.QLabel(Dialog)
        self.labelStaticL11.setGeometry(QtCore.QRect(20, 20, 115, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL11.setFont(font)
        self.labelStaticL11.setObjectName("labelStaticL11")
        self.labelStaticL14 = QtWidgets.QLabel(Dialog)
        self.labelStaticL14.setGeometry(QtCore.QRect(20, 140, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL14.setFont(font)
        self.labelStaticL14.setObjectName("labelStaticL14")
        self.dateEditL1 = QtWidgets.QDateEdit(Dialog)
        self.dateEditL1.setGeometry(QtCore.QRect(180, 110, 151, 22))
        self.dateEditL1.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEditL1.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditL1.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEditL1.setCalendarPopup(True)
        self.dateEditL1.setObjectName("dateEditL1")
        self.lineEditL1Credit = QtWidgets.QLineEdit(Dialog)
        self.lineEditL1Credit.setGeometry(QtCore.QRect(180, 260, 151, 20))
        self.lineEditL1Credit.setText("")
        self.lineEditL1Credit.setMaxLength(20)
        self.lineEditL1Credit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditL1Credit.setObjectName("lineEditL1Credit")
        self.pushButtonClearL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonClearL1.setGeometry(QtCore.QRect(1091, 290, 100, 25))
        self.pushButtonClearL1.setObjectName("pushButtonClearL1")
        self.pushButtonUploadL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonUploadL1.setGeometry(QtCore.QRect(830, 223, 80, 22))
        self.pushButtonUploadL1.setObjectName("pushButtonUploadL1")
        self.radioButtonL1Pending = QtWidgets.QRadioButton(Dialog)
        self.radioButtonL1Pending.setGeometry(QtCore.QRect(829, 170, 100, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonL1Pending.setFont(font)
        self.radioButtonL1Pending.setObjectName("radioButtonL1Pending")
        self.tableWidgetL1 = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetL1.setGeometry(QtCore.QRect(20, 320, 1170, 426))
        self.tableWidgetL1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetL1.setLineWidth(2)
        self.tableWidgetL1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetL1.setAlternatingRowColors(True)
        self.tableWidgetL1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetL1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetL1.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidgetL1.setShowGrid(False)
        self.tableWidgetL1.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetL1.setObjectName("tableWidgetL1")
        self.tableWidgetL1.setColumnCount(0)
        self.tableWidgetL1.setRowCount(0)
        self.tableWidgetL1.horizontalHeader().setStretchLastSection(True)
        self.labelStaticL15 = QtWidgets.QLabel(Dialog)
        self.labelStaticL15.setGeometry(QtCore.QRect(20, 170, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL15.setFont(font)
        self.labelStaticL15.setObjectName("labelStaticL15")
        self.pushButtonAddL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddL1.setGeometry(QtCore.QRect(591, 290, 200, 25))
        self.pushButtonAddL1.setObjectName("pushButtonAddL1")
        self.pushButtonDeleteL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDeleteL1.setGeometry(QtCore.QRect(991, 290, 100, 25))
        self.pushButtonDeleteL1.setObjectName("pushButtonDeleteL1")
        self.textEditL1Notes = QtWidgets.QTextEdit(Dialog)
        self.textEditL1Notes.setGeometry(QtCore.QRect(829, 110, 321, 50))
        self.textEditL1Notes.setObjectName("textEditL1Notes")
        self.lineEditL1TD = QtWidgets.QLineEdit(Dialog)
        self.lineEditL1TD.setGeometry(QtCore.QRect(180, 170, 250, 20))
        self.lineEditL1TD.setMaxLength(40)
        self.lineEditL1TD.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditL1TD.setObjectName("lineEditL1TD")
        self.pushButtonCatL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonCatL1.setGeometry(QtCore.QRect(340, 200, 91, 23))
        self.pushButtonCatL1.setObjectName("pushButtonCatL1")
        self.pushButtonSelectL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectL1.setGeometry(QtCore.QRect(791, 290, 100, 25))
        self.pushButtonSelectL1.setObjectName("pushButtonSelectL1")
        self.lineEditL1Debit = QtWidgets.QLineEdit(Dialog)
        self.lineEditL1Debit.setGeometry(QtCore.QRect(180, 230, 151, 20))
        self.lineEditL1Debit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditL1Debit.setInputMask("")
        self.lineEditL1Debit.setText("")
        self.lineEditL1Debit.setMaxLength(20)
        self.lineEditL1Debit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditL1Debit.setObjectName("lineEditL1Debit")
        self.pushButtonNewL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonNewL1.setGeometry(QtCore.QRect(560, 20, 100, 25))
        self.pushButtonNewL1.setObjectName("pushButtonNewL1")
        self.pushButtonUpdateL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonUpdateL1.setGeometry(QtCore.QRect(891, 290, 100, 25))
        self.pushButtonUpdateL1.setObjectName("pushButtonUpdateL1")
        self.labelStaticL16 = QtWidgets.QLabel(Dialog)
        self.labelStaticL16.setGeometry(QtCore.QRect(20, 200, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL16.setFont(font)
        self.labelStaticL16.setObjectName("labelStaticL16")
        self.labelL1Status = QtWidgets.QLabel(Dialog)
        self.labelL1Status.setGeometry(QtCore.QRect(689, 170, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelL1Status.setFont(font)
        self.labelL1Status.setObjectName("labelL1Status")
        self.lineEditL1TM = QtWidgets.QLineEdit(Dialog)
        self.lineEditL1TM.setGeometry(QtCore.QRect(180, 140, 151, 20))
        self.lineEditL1TM.setMaxLength(20)
        self.lineEditL1TM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditL1TM.setObjectName("lineEditL1TM")
        self.labelL1Reciept = QtWidgets.QLabel(Dialog)
        self.labelL1Reciept.setGeometry(QtCore.QRect(689, 200, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelL1Reciept.setFont(font)
        self.labelL1Reciept.setObjectName("labelL1Reciept")
        self.labelStaticL17 = QtWidgets.QLabel(Dialog)
        self.labelStaticL17.setGeometry(QtCore.QRect(20, 230, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL17.setFont(font)
        self.labelStaticL17.setObjectName("labelStaticL17")
        self.labelStaticL18 = QtWidgets.QLabel(Dialog)
        self.labelStaticL18.setGeometry(QtCore.QRect(20, 260, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL18.setFont(font)
        self.labelStaticL18.setObjectName("labelStaticL18")
        self.comboBoxL1 = QtWidgets.QComboBox(Dialog)
        self.comboBoxL1.setGeometry(QtCore.QRect(140, 20, 400, 24))
        self.comboBoxL1.setObjectName("comboBoxL1")
        self.lineEditReceiptL1 = QtWidgets.QLineEdit(Dialog)
        self.lineEditReceiptL1.setEnabled(False)
        self.lineEditReceiptL1.setGeometry(QtCore.QRect(829, 200, 321, 20))
        self.lineEditReceiptL1.setObjectName("lineEditReceiptL1")
        self.comboBoxL1C = QtWidgets.QComboBox(Dialog)
        self.comboBoxL1C.setGeometry(QtCore.QRect(180, 200, 150, 22))
        self.comboBoxL1C.setObjectName("comboBoxL1C")
        self.pushButtonDisplayL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDisplayL1.setEnabled(True)
        self.pushButtonDisplayL1.setGeometry(QtCore.QRect(910, 223, 80, 22))
        self.pushButtonDisplayL1.setObjectName("pushButtonDisplayL1")
        self.radioButtonL1Posted = QtWidgets.QRadioButton(Dialog)
        self.radioButtonL1Posted.setGeometry(QtCore.QRect(919, 170, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonL1Posted.setFont(font)
        self.radioButtonL1Posted.setObjectName("radioButtonL1Posted")
        self.labelStaticL13 = QtWidgets.QLabel(Dialog)
        self.labelStaticL13.setGeometry(QtCore.QRect(20, 110, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL13.setFont(font)
        self.labelStaticL13.setObjectName("labelStaticL13")
        self.labelL1Notes = QtWidgets.QLabel(Dialog)
        self.labelL1Notes.setGeometry(QtCore.QRect(689, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelL1Notes.setFont(font)
        self.labelL1Notes.setObjectName("labelL1Notes")
        self.frameLeft = QtWidgets.QFrame(Dialog)
        self.frameLeft.setGeometry(QtCore.QRect(208, 60, 275, 40))
        self.frameLeft.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameLeft.setLineWidth(1)
        self.frameLeft.setObjectName("frameLeft")
        self.labelStaticL12 = QtWidgets.QLabel(self.frameLeft)
        self.labelStaticL12.setGeometry(QtCore.QRect(0, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelStaticL12.setFont(font)
        self.labelStaticL12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStaticL12.setObjectName("labelStaticL12")
        self.labelL1NV = QtWidgets.QLabel(self.frameLeft)
        self.labelL1NV.setGeometry(QtCore.QRect(137, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelL1NV.setFont(font)
        self.labelL1NV.setText("")
        self.labelL1NV.setAlignment(QtCore.Qt.AlignCenter)
        self.labelL1NV.setObjectName("labelL1NV")
        self.frameMiddle = QtWidgets.QFrame(Dialog)
        self.frameMiddle.setGeometry(QtCore.QRect(493, 60, 225, 40))
        self.frameMiddle.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameMiddle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameMiddle.setLineWidth(1)
        self.frameMiddle.setObjectName("frameMiddle")
        self.labelVariable1A = QtWidgets.QLabel(self.frameMiddle)
        self.labelVariable1A.setGeometry(QtCore.QRect(0, 0, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable1A.setFont(font)
        self.labelVariable1A.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable1A.setObjectName("labelVariable1A")
        self.labelVariable1B = QtWidgets.QLabel(self.frameMiddle)
        self.labelVariable1B.setGeometry(QtCore.QRect(120, 0, 105, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable1B.setFont(font)
        self.labelVariable1B.setText("")
        self.labelVariable1B.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable1B.setObjectName("labelVariable1B")
        self.frameRight = QtWidgets.QFrame(Dialog)
        self.frameRight.setGeometry(QtCore.QRect(727, 60, 275, 40))
        self.frameRight.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameRight.setLineWidth(1)
        self.frameRight.setObjectName("frameRight")
        self.labelVariable2B = QtWidgets.QLabel(self.frameRight)
        self.labelVariable2B.setGeometry(QtCore.QRect(137, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable2B.setFont(font)
        self.labelVariable2B.setText("")
        self.labelVariable2B.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable2B.setObjectName("labelVariable2B")
        self.labelVariable2A = QtWidgets.QLabel(self.frameRight)
        self.labelVariable2A.setGeometry(QtCore.QRect(0, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable2A.setFont(font)
        self.labelVariable2A.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable2A.setObjectName("labelVariable2A")
        self.pushButtonRClearL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonRClearL1.setGeometry(QtCore.QRect(990, 223, 80, 22))
        self.pushButtonRClearL1.setObjectName("pushButtonRClearL1")
        self.pushButtonRDeleteL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonRDeleteL1.setGeometry(QtCore.QRect(1070, 223, 80, 22))
        self.pushButtonRDeleteL1.setObjectName("pushButtonRDeleteL1")
        self.pushButtonDispRangL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDispRangL1.setGeometry(QtCore.QRect(1060, 750, 131, 25))
        self.pushButtonDispRangL1.setObjectName("pushButtonDispRangL1")
        self.pushButtonSearchL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonSearchL1.setGeometry(QtCore.QRect(930, 750, 131, 25))
        self.pushButtonSearchL1.setObjectName("pushButtonSearchL1")
        self.frameLeft.raise_()
        self.labelStaticL11.raise_()
        self.labelStaticL14.raise_()
        self.dateEditL1.raise_()
        self.lineEditL1Credit.raise_()
        self.pushButtonClearL1.raise_()
        self.pushButtonUploadL1.raise_()
        self.radioButtonL1Pending.raise_()
        self.tableWidgetL1.raise_()
        self.labelStaticL15.raise_()
        self.pushButtonAddL1.raise_()
        self.pushButtonDeleteL1.raise_()
        self.textEditL1Notes.raise_()
        self.lineEditL1TD.raise_()
        self.pushButtonCatL1.raise_()
        self.pushButtonSelectL1.raise_()
        self.lineEditL1Debit.raise_()
        self.pushButtonNewL1.raise_()
        self.pushButtonUpdateL1.raise_()
        self.labelStaticL16.raise_()
        self.labelL1Status.raise_()
        self.lineEditL1TM.raise_()
        self.labelL1Reciept.raise_()
        self.labelStaticL17.raise_()
        self.labelStaticL18.raise_()
        self.comboBoxL1.raise_()
        self.lineEditReceiptL1.raise_()
        self.comboBoxL1C.raise_()
        self.pushButtonDisplayL1.raise_()
        self.radioButtonL1Posted.raise_()
        self.labelStaticL13.raise_()
        self.labelL1Notes.raise_()
        self.frameMiddle.raise_()
        self.frameRight.raise_()
        self.pushButtonRClearL1.raise_()
        self.pushButtonRDeleteL1.raise_()
        self.pushButtonDispRangL1.raise_()
        self.pushButtonSearchL1.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBoxL1, self.pushButtonNewL1)
        Dialog.setTabOrder(self.pushButtonNewL1, self.dateEditL1)
        Dialog.setTabOrder(self.dateEditL1, self.lineEditL1TM)
        Dialog.setTabOrder(self.lineEditL1TM, self.lineEditL1TD)
        Dialog.setTabOrder(self.lineEditL1TD, self.comboBoxL1C)
        Dialog.setTabOrder(self.comboBoxL1C, self.pushButtonCatL1)
        Dialog.setTabOrder(self.pushButtonCatL1, self.lineEditL1Debit)
        Dialog.setTabOrder(self.lineEditL1Debit, self.lineEditL1Credit)
        Dialog.setTabOrder(self.lineEditL1Credit, self.textEditL1Notes)
        Dialog.setTabOrder(self.textEditL1Notes, self.radioButtonL1Pending)
        Dialog.setTabOrder(self.radioButtonL1Pending, self.radioButtonL1Posted)
        Dialog.setTabOrder(self.radioButtonL1Posted, self.pushButtonUploadL1)
        Dialog.setTabOrder(self.pushButtonUploadL1, self.pushButtonDisplayL1)
        Dialog.setTabOrder(self.pushButtonDisplayL1, self.pushButtonAddL1)
        Dialog.setTabOrder(self.pushButtonAddL1, self.pushButtonSelectL1)
        Dialog.setTabOrder(self.pushButtonSelectL1, self.pushButtonUpdateL1)
        Dialog.setTabOrder(self.pushButtonUpdateL1, self.pushButtonDeleteL1)
        Dialog.setTabOrder(self.pushButtonDeleteL1, self.pushButtonClearL1)
        Dialog.setTabOrder(self.pushButtonClearL1, self.tableWidgetL1)
        Dialog.setTabOrder(self.tableWidgetL1, self.lineEditReceiptL1)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelStaticL11.setText(_translate("Dialog", "Active Account:"))
        self.labelStaticL14.setText(_translate("Dialog", "  Transaction Method:"))
        self.dateEditL1.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd"))
        self.lineEditL1Credit.setPlaceholderText(_translate("Dialog", "0.00"))
        self.pushButtonClearL1.setText(_translate("Dialog", "Clear"))
        self.pushButtonUploadL1.setText(_translate("Dialog", "Upload"))
        self.radioButtonL1Pending.setText(_translate("Dialog", "Pending"))
        self.tableWidgetL1.setSortingEnabled(False)
        self.labelStaticL15.setText(_translate("Dialog", "*Transaction Description:"))
        self.pushButtonAddL1.setText(_translate("Dialog", "Add Transaction"))
        self.pushButtonDeleteL1.setText(_translate("Dialog", "Delete "))
        self.textEditL1Notes.setPlaceholderText(_translate("Dialog", "(Max 150 Characters)"))
        self.lineEditL1TD.setPlaceholderText(_translate("Dialog", "(Max 40 Characters)"))
        self.pushButtonCatL1.setText(_translate("Dialog", "Modify"))
        self.pushButtonSelectL1.setText(_translate("Dialog", "Select"))
        self.lineEditL1Debit.setPlaceholderText(_translate("Dialog", "0.00"))
        self.pushButtonNewL1.setText(_translate("Dialog", "Modify"))
        self.pushButtonUpdateL1.setText(_translate("Dialog", "Update "))
        self.labelStaticL16.setText(_translate("Dialog", "*Category:"))
        self.labelL1Status.setText(_translate("Dialog", "*Transaction Status:"))
        self.lineEditL1TM.setPlaceholderText(_translate("Dialog", "(Max 20 Characters)"))
        self.labelL1Reciept.setText(_translate("Dialog", "  Receipt:"))
        self.labelStaticL17.setText(_translate("Dialog", "  Debit (-):"))
        self.labelStaticL18.setText(_translate("Dialog", "  Credit (+):"))
        self.pushButtonDisplayL1.setText(_translate("Dialog", "Display"))
        self.radioButtonL1Posted.setText(_translate("Dialog", "Posted"))
        self.labelStaticL13.setText(_translate("Dialog", "*Transaction Date:"))
        self.labelL1Notes.setText(_translate("Dialog", "  Additional Notes:"))
        self.labelStaticL12.setText(_translate("Dialog", "Account Balance:"))
        self.labelVariable1A.setText(_translate("Dialog", "Interest Rate:"))
        self.labelVariable2A.setText(_translate("Dialog", "Maturity Date:"))
        self.pushButtonRClearL1.setText(_translate("Dialog", "Clear"))
        self.pushButtonRDeleteL1.setText(_translate("Dialog", "Delete"))
        self.pushButtonDispRangL1.setText(_translate("Dialog", "Display Range"))
        self.pushButtonSearchL1.setText(_translate("Dialog", "Search"))


