# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ledger2Ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 798)
        self.labelStaticL21 = QtWidgets.QLabel(Dialog)
        self.labelStaticL21.setGeometry(QtCore.QRect(20, 20, 115, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL21.setFont(font)
        self.labelStaticL21.setObjectName("labelStaticL21")
        self.dateEditL2 = QtWidgets.QDateEdit(Dialog)
        self.dateEditL2.setGeometry(QtCore.QRect(180, 110, 151, 22))
        self.dateEditL2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEditL2.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditL2.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEditL2.setCalendarPopup(True)
        self.dateEditL2.setObjectName("dateEditL2")
        self.lineEditL2Credit = QtWidgets.QLineEdit(Dialog)
        self.lineEditL2Credit.setGeometry(QtCore.QRect(180, 230, 151, 20))
        self.lineEditL2Credit.setText("")
        self.lineEditL2Credit.setMaxLength(20)
        self.lineEditL2Credit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditL2Credit.setObjectName("lineEditL2Credit")
        self.pushButtonClearL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonClearL2.setGeometry(QtCore.QRect(966, 290, 75, 25))
        self.pushButtonClearL2.setObjectName("pushButtonClearL2")
        self.pushButtonUploadL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonUploadL2.setGeometry(QtCore.QRect(828, 253, 82, 22))
        self.pushButtonUploadL2.setObjectName("pushButtonUploadL2")
        self.radioButtonL2Pending = QtWidgets.QRadioButton(Dialog)
        self.radioButtonL2Pending.setGeometry(QtCore.QRect(829, 200, 100, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonL2Pending.setFont(font)
        self.radioButtonL2Pending.setObjectName("radioButtonL2Pending")
        self.tableWidgetL2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetL2.setGeometry(QtCore.QRect(20, 320, 1170, 426))
        self.tableWidgetL2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetL2.setLineWidth(2)
        self.tableWidgetL2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetL2.setAlternatingRowColors(True)
        self.tableWidgetL2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetL2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetL2.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidgetL2.setShowGrid(False)
        self.tableWidgetL2.setObjectName("tableWidgetL2")
        self.tableWidgetL2.setColumnCount(0)
        self.tableWidgetL2.setRowCount(0)
        self.tableWidgetL2.horizontalHeader().setStretchLastSection(True)
        self.labelStaticL25 = QtWidgets.QLabel(Dialog)
        self.labelStaticL25.setGeometry(QtCore.QRect(20, 140, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL25.setFont(font)
        self.labelStaticL25.setObjectName("labelStaticL25")
        self.pushButtonAddL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonAddL2.setGeometry(QtCore.QRect(591, 290, 150, 25))
        self.pushButtonAddL2.setObjectName("pushButtonAddL2")
        self.pushButtonDeleteL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDeleteL2.setGeometry(QtCore.QRect(891, 290, 75, 25))
        self.pushButtonDeleteL2.setObjectName("pushButtonDeleteL2")
        self.lineEditL2TD = QtWidgets.QLineEdit(Dialog)
        self.lineEditL2TD.setGeometry(QtCore.QRect(180, 140, 250, 20))
        self.lineEditL2TD.setMaxLength(40)
        self.lineEditL2TD.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditL2TD.setObjectName("lineEditL2TD")
        self.pushButtonCatL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonCatL2.setGeometry(QtCore.QRect(340, 170, 91, 23))
        self.pushButtonCatL2.setObjectName("pushButtonCatL2")
        self.pushButtonSelectL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectL2.setGeometry(QtCore.QRect(741, 290, 75, 25))
        self.pushButtonSelectL2.setObjectName("pushButtonSelectL2")
        self.lineEditL2Debit = QtWidgets.QLineEdit(Dialog)
        self.lineEditL2Debit.setGeometry(QtCore.QRect(180, 200, 151, 20))
        self.lineEditL2Debit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditL2Debit.setInputMask("")
        self.lineEditL2Debit.setText("")
        self.lineEditL2Debit.setMaxLength(20)
        self.lineEditL2Debit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditL2Debit.setObjectName("lineEditL2Debit")
        self.pushButtonNewL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonNewL2.setGeometry(QtCore.QRect(560, 20, 100, 25))
        self.pushButtonNewL2.setObjectName("pushButtonNewL2")
        self.pushButtonUpdateL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonUpdateL2.setGeometry(QtCore.QRect(816, 290, 75, 25))
        self.pushButtonUpdateL2.setObjectName("pushButtonUpdateL2")
        self.labelStaticL26 = QtWidgets.QLabel(Dialog)
        self.labelStaticL26.setGeometry(QtCore.QRect(20, 170, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL26.setFont(font)
        self.labelStaticL26.setObjectName("labelStaticL26")
        self.labelL2Status = QtWidgets.QLabel(Dialog)
        self.labelL2Status.setGeometry(QtCore.QRect(689, 200, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelL2Status.setFont(font)
        self.labelL2Status.setObjectName("labelL2Status")
        self.labelL2Reciept = QtWidgets.QLabel(Dialog)
        self.labelL2Reciept.setGeometry(QtCore.QRect(689, 230, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelL2Reciept.setFont(font)
        self.labelL2Reciept.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelL2Reciept.setObjectName("labelL2Reciept")
        self.labelStaticL27 = QtWidgets.QLabel(Dialog)
        self.labelStaticL27.setGeometry(QtCore.QRect(20, 200, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL27.setFont(font)
        self.labelStaticL27.setObjectName("labelStaticL27")
        self.labelStaticL28 = QtWidgets.QLabel(Dialog)
        self.labelStaticL28.setGeometry(QtCore.QRect(20, 230, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL28.setFont(font)
        self.labelStaticL28.setObjectName("labelStaticL28")
        self.comboBoxL2 = QtWidgets.QComboBox(Dialog)
        self.comboBoxL2.setGeometry(QtCore.QRect(140, 20, 400, 24))
        self.comboBoxL2.setObjectName("comboBoxL2")
        self.lineEditReceiptL2 = QtWidgets.QLineEdit(Dialog)
        self.lineEditReceiptL2.setEnabled(False)
        self.lineEditReceiptL2.setGeometry(QtCore.QRect(829, 230, 321, 20))
        self.lineEditReceiptL2.setObjectName("lineEditReceiptL2")
        self.comboBoxL2C = QtWidgets.QComboBox(Dialog)
        self.comboBoxL2C.setGeometry(QtCore.QRect(180, 170, 150, 22))
        self.comboBoxL2C.setObjectName("comboBoxL2C")
        self.pushButtonDisplayL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDisplayL2.setEnabled(True)
        self.pushButtonDisplayL2.setGeometry(QtCore.QRect(910, 253, 80, 22))
        self.pushButtonDisplayL2.setObjectName("pushButtonDisplayL2")
        self.radioButtonL2Posted = QtWidgets.QRadioButton(Dialog)
        self.radioButtonL2Posted.setGeometry(QtCore.QRect(919, 200, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButtonL2Posted.setFont(font)
        self.radioButtonL2Posted.setObjectName("radioButtonL2Posted")
        self.labelStaticL23 = QtWidgets.QLabel(Dialog)
        self.labelStaticL23.setGeometry(QtCore.QRect(20, 110, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL23.setFont(font)
        self.labelStaticL23.setObjectName("labelStaticL23")
        self.labelStaticL210 = QtWidgets.QLabel(Dialog)
        self.labelStaticL210.setGeometry(QtCore.QRect(949, 110, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL210.setFont(font)
        self.labelStaticL210.setObjectName("labelStaticL210")
        self.lineEditL2Sold = QtWidgets.QLineEdit(Dialog)
        self.lineEditL2Sold.setGeometry(QtCore.QRect(1047, 110, 100, 20))
        self.lineEditL2Sold.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditL2Sold.setInputMask("")
        self.lineEditL2Sold.setText("")
        self.lineEditL2Sold.setMaxLength(20)
        self.lineEditL2Sold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditL2Sold.setObjectName("lineEditL2Sold")
        self.lineEditL2Purchase = QtWidgets.QLineEdit(Dialog)
        self.lineEditL2Purchase.setGeometry(QtCore.QRect(829, 110, 101, 20))
        self.lineEditL2Purchase.setText("")
        self.lineEditL2Purchase.setMaxLength(20)
        self.lineEditL2Purchase.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditL2Purchase.setObjectName("lineEditL2Purchase")
        self.labelStaticL29 = QtWidgets.QLabel(Dialog)
        self.labelStaticL29.setGeometry(QtCore.QRect(689, 110, 115, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL29.setFont(font)
        self.labelStaticL29.setObjectName("labelStaticL29")
        self.textEditL2Notes = QtWidgets.QTextEdit(Dialog)
        self.textEditL2Notes.setGeometry(QtCore.QRect(829, 140, 321, 50))
        self.textEditL2Notes.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEditL2Notes.setObjectName("textEditL2Notes")
        self.labelL2Notes = QtWidgets.QLabel(Dialog)
        self.labelL2Notes.setGeometry(QtCore.QRect(689, 140, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelL2Notes.setFont(font)
        self.labelL2Notes.setObjectName("labelL2Notes")
        self.labelStaticL212 = QtWidgets.QLabel(Dialog)
        self.labelStaticL212.setGeometry(QtCore.QRect(20, 260, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStaticL212.setFont(font)
        self.labelStaticL212.setObjectName("labelStaticL212")
        self.lineEditL2Price = QtWidgets.QLineEdit(Dialog)
        self.lineEditL2Price.setGeometry(QtCore.QRect(180, 260, 151, 20))
        self.lineEditL2Price.setText("")
        self.lineEditL2Price.setMaxLength(20)
        self.lineEditL2Price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditL2Price.setObjectName("lineEditL2Price")
        self.pushButtonUpdatePriceL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonUpdatePriceL2.setGeometry(QtCore.QRect(1041, 290, 150, 25))
        self.pushButtonUpdatePriceL2.setObjectName("pushButtonUpdatePriceL2")
        self.frameRight = QtWidgets.QFrame(Dialog)
        self.frameRight.setGeometry(QtCore.QRect(727, 60, 275, 40))
        self.frameRight.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameRight.setLineWidth(1)
        self.frameRight.setObjectName("frameRight")
        self.labelVariable2B = QtWidgets.QLabel(self.frameRight)
        self.labelVariable2B.setGeometry(QtCore.QRect(137, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable2B.setFont(font)
        self.labelVariable2B.setText("")
        self.labelVariable2B.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable2B.setObjectName("labelVariable2B")
        self.labelVariable2A = QtWidgets.QLabel(self.frameRight)
        self.labelVariable2A.setGeometry(QtCore.QRect(0, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable2A.setFont(font)
        self.labelVariable2A.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable2A.setObjectName("labelVariable2A")
        self.frameMiddle = QtWidgets.QFrame(Dialog)
        self.frameMiddle.setGeometry(QtCore.QRect(493, 60, 225, 40))
        self.frameMiddle.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameMiddle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameMiddle.setLineWidth(1)
        self.frameMiddle.setObjectName("frameMiddle")
        self.labelVariable1A = QtWidgets.QLabel(self.frameMiddle)
        self.labelVariable1A.setGeometry(QtCore.QRect(0, 0, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable1A.setFont(font)
        self.labelVariable1A.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable1A.setObjectName("labelVariable1A")
        self.labelVariable1B = QtWidgets.QLabel(self.frameMiddle)
        self.labelVariable1B.setGeometry(QtCore.QRect(120, 0, 105, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVariable1B.setFont(font)
        self.labelVariable1B.setText("")
        self.labelVariable1B.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVariable1B.setObjectName("labelVariable1B")
        self.frameLeft = QtWidgets.QFrame(Dialog)
        self.frameLeft.setGeometry(QtCore.QRect(208, 60, 275, 40))
        self.frameLeft.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameLeft.setLineWidth(1)
        self.frameLeft.setObjectName("frameLeft")
        self.labelStaticL12 = QtWidgets.QLabel(self.frameLeft)
        self.labelStaticL12.setGeometry(QtCore.QRect(0, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelStaticL12.setFont(font)
        self.labelStaticL12.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStaticL12.setObjectName("labelStaticL12")
        self.labelL2NV = QtWidgets.QLabel(self.frameLeft)
        self.labelL2NV.setGeometry(QtCore.QRect(137, 0, 137, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelL2NV.setFont(font)
        self.labelL2NV.setText("")
        self.labelL2NV.setAlignment(QtCore.Qt.AlignCenter)
        self.labelL2NV.setObjectName("labelL2NV")
        self.pushButtonSearchL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonSearchL1.setGeometry(QtCore.QRect(930, 750, 131, 25))
        self.pushButtonSearchL1.setObjectName("pushButtonSearchL1")
        self.pushButtonDispRangL1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDispRangL1.setGeometry(QtCore.QRect(1060, 750, 131, 25))
        self.pushButtonDispRangL1.setObjectName("pushButtonDispRangL1")
        self.pushButtonRClearL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonRClearL2.setGeometry(QtCore.QRect(990, 253, 80, 22))
        self.pushButtonRClearL2.setObjectName("pushButtonRClearL2")
        self.pushButtonRDeleteL2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonRDeleteL2.setGeometry(QtCore.QRect(1070, 253, 81, 22))
        self.pushButtonRDeleteL2.setObjectName("pushButtonRDeleteL2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBoxL2, self.pushButtonNewL2)
        Dialog.setTabOrder(self.pushButtonNewL2, self.dateEditL2)
        Dialog.setTabOrder(self.dateEditL2, self.lineEditL2TD)
        Dialog.setTabOrder(self.lineEditL2TD, self.comboBoxL2C)
        Dialog.setTabOrder(self.comboBoxL2C, self.pushButtonCatL2)
        Dialog.setTabOrder(self.pushButtonCatL2, self.lineEditL2Debit)
        Dialog.setTabOrder(self.lineEditL2Debit, self.lineEditL2Credit)
        Dialog.setTabOrder(self.lineEditL2Credit, self.lineEditL2Price)
        Dialog.setTabOrder(self.lineEditL2Price, self.lineEditL2Purchase)
        Dialog.setTabOrder(self.lineEditL2Purchase, self.lineEditL2Sold)
        Dialog.setTabOrder(self.lineEditL2Sold, self.textEditL2Notes)
        Dialog.setTabOrder(self.textEditL2Notes, self.radioButtonL2Pending)
        Dialog.setTabOrder(self.radioButtonL2Pending, self.radioButtonL2Posted)
        Dialog.setTabOrder(self.radioButtonL2Posted, self.pushButtonUploadL2)
        Dialog.setTabOrder(self.pushButtonUploadL2, self.pushButtonDisplayL2)
        Dialog.setTabOrder(self.pushButtonDisplayL2, self.pushButtonAddL2)
        Dialog.setTabOrder(self.pushButtonAddL2, self.pushButtonSelectL2)
        Dialog.setTabOrder(self.pushButtonSelectL2, self.pushButtonUpdateL2)
        Dialog.setTabOrder(self.pushButtonUpdateL2, self.pushButtonDeleteL2)
        Dialog.setTabOrder(self.pushButtonDeleteL2, self.pushButtonClearL2)
        Dialog.setTabOrder(self.pushButtonClearL2, self.pushButtonUpdatePriceL2)
        Dialog.setTabOrder(self.pushButtonUpdatePriceL2, self.tableWidgetL2)
        Dialog.setTabOrder(self.tableWidgetL2, self.lineEditReceiptL2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelStaticL21.setText(_translate("Dialog", "Active Account:"))
        self.dateEditL2.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd"))
        self.lineEditL2Credit.setPlaceholderText(_translate("Dialog", "0.00"))
        self.pushButtonClearL2.setText(_translate("Dialog", "Clear"))
        self.pushButtonUploadL2.setText(_translate("Dialog", "Upload"))
        self.radioButtonL2Pending.setText(_translate("Dialog", "Pending"))
        self.tableWidgetL2.setSortingEnabled(True)
        self.labelStaticL25.setText(_translate("Dialog", "*Transaction Description:"))
        self.pushButtonAddL2.setText(_translate("Dialog", "Add Transaction"))
        self.pushButtonDeleteL2.setText(_translate("Dialog", "Delete "))
        self.lineEditL2TD.setPlaceholderText(_translate("Dialog", "(Max 40 Characters)"))
        self.pushButtonCatL2.setText(_translate("Dialog", "Modify"))
        self.pushButtonSelectL2.setText(_translate("Dialog", "Select"))
        self.lineEditL2Debit.setPlaceholderText(_translate("Dialog", "0.00"))
        self.pushButtonNewL2.setText(_translate("Dialog", "Modify"))
        self.pushButtonUpdateL2.setText(_translate("Dialog", "Update "))
        self.labelStaticL26.setText(_translate("Dialog", "*Category:"))
        self.labelL2Status.setText(_translate("Dialog", "*Transaction Status:"))
        self.labelL2Reciept.setText(_translate("Dialog", "  Receipt:"))
        self.labelStaticL27.setText(_translate("Dialog", "  Debit (-):"))
        self.labelStaticL28.setText(_translate("Dialog", "  Credit (+):"))
        self.pushButtonDisplayL2.setText(_translate("Dialog", "Display"))
        self.radioButtonL2Posted.setText(_translate("Dialog", "Posted"))
        self.labelStaticL23.setText(_translate("Dialog", "*Transaction Date:"))
        self.labelStaticL210.setText(_translate("Dialog", "Shares Sold:"))
        self.lineEditL2Sold.setPlaceholderText(_translate("Dialog", "0.0000"))
        self.lineEditL2Purchase.setPlaceholderText(_translate("Dialog", "0.0000"))
        self.labelStaticL29.setText(_translate("Dialog", "  Shares Purchased:"))
        self.textEditL2Notes.setPlaceholderText(_translate("Dialog", "(Max 150 Characters)"))
        self.labelL2Notes.setText(_translate("Dialog", "  Additional Notes:"))
        self.labelStaticL212.setText(_translate("Dialog", "*Price/Share"))
        self.lineEditL2Price.setPlaceholderText(_translate("Dialog", "0.0000"))
        self.pushButtonUpdatePriceL2.setText(_translate("Dialog", "Update Stock Price"))
        self.labelVariable2A.setText(_translate("Dialog", "Share Price:"))
        self.labelVariable1A.setText(_translate("Dialog", "Share Balance:"))
        self.labelStaticL12.setText(_translate("Dialog", "Account Balance:"))
        self.pushButtonSearchL1.setText(_translate("Dialog", "Search"))
        self.pushButtonDispRangL1.setText(_translate("Dialog", "Display Range"))
        self.pushButtonRClearL2.setText(_translate("Dialog", "Clear"))
        self.pushButtonRDeleteL2.setText(_translate("Dialog", "Delete"))

